### ISSUE TITLE
ReaPack Compatibility

### ISSUE THREAD

**Issue by X-Raym** [kawaCat/ReaScript-MIDI#2]
Hi !

Thanks you for sharing !

Are you aware of ReaPack, the extension ?
It could be interesting to make this scripts ReaPack compatible, so that they could be downloaded and installed right from REAPER.

Anyway, you should consider open a thread on JSFX/ReaScript forum on cockos.forum.com to speak about your scripts, I'm sure a lot of people will enjoy them!

**Comment by kawaCat** [comment]
thankyou for message !

Thanks for telling me about ReaPack. I could have made my scripts compatible with ReaPack if I had known it then. 
Making them compatible with ReaPack from now on will take a while as I like to do it. 

Opening a thread and speaking about scripts are tempting, but I am so poor at English that I by myself can't go thru English communication. 
Actually, this is not direct writing of mine but the translation by the other helping me to reply to you. 
I wish I enjoyed participation to the forum, but I am just satisfied with encouragement from Reaper users like you.

(thank you 408:translation at 2ch)

**Comment by X-Raym** [comment]
Being member of a forum is a good way to practice english :P I'm not native english speaker either.

Making your scripts ReaPack compatible is technically not that hard :)
[Here](http://www.extremraym.com/en/reapack) is an article which I plan to release at ReaPack v1.0 release (when the beta will be over), explaining the whole thing. It's in english, but you can take your time to read it.

You can go on forum on tell a simple message like

> Here is my ReaScripts repo. Enjoy. :)

But I can open this thread for you if you really prefer.

And if you don't want to make your scripts ReaPack compatible it is ok too, of course, you are free to share your scripts the way you like !

Side question: what is the state of Japanese translation of REAPER ? is it easily accessible for Japanese speakers ?

**Comment by kawaCat** [comment]
I ask you to open the thread if you don't mind though I won't say much there and only read it the most of time; some opinion may affect what I make in better way like you did. 
Anyway, I almost have made my midi script compatible with ReaPack now. 

I don't use Japanese translation of REAPER and thus don't know much about it. I know some who got Japanese Language Pack, but making it work seems not so easy. Actually the language is always the big issue when Japanese try REAPER.

(thank you 413:translation at 2ch)

and I tried to ReaPack ! :) 

github ( https://github.com/kawaCat/ReaScript-MidiPack )
repository ( https://github.com/kawaCat/ReaScript-MidiPack/raw/master/index.xml )

is this my repository is working  with no poroblems ?

**Comment by X-Raym** [comment]
Thanks for your collaboration :)
I created the REAPER forum thread for you : Scripts: [Reascript pack from Kawa](http://forum.cockos.com/showthread.php?p=1683960#post1683960) 

A lot of people will really enjoy it :)

---------
For Reapack compatibility : usually, scripts which have to be imported in the MIDI Editor section of the Action list have to be in the `MIDI Editor` subfolder from the root. Scripts for the Main section are just in any subfolder.
I don't know why, but in your case, only the MIDI scripts get imported in the right place, but your MAIN and GUI scripts didn't get imported. Maybe you index.xml is not up to date with the repo files structures, or maybe there is another problem.
But you did the hardest part, it will work fine :P

---------
for the language, I know there has been some improvements on non-occidental characters support but maintaining a REAPER translation is certainly not an easy task. It seems that there is an old japanese language pack online, but maybe it is not necessary.

**Comment by kawaCat** [comment]
Im sorry to reply late.  

MAIN and others but MIDI scripts are not dun yet. I will announce the completion as soon as I finish all the work. 
Anyway I really appreciate you having made the thread for me and the users of my scripts. 
The translation guy is also checking the thread. Now he can answer in the thread hearing my words when you ask in the thread.

(thank you 418:translation at 2ch) 

thank you ! :)

**Comment by X-Raym** [comment]
You are welcome !

Be careful with the last version of reapack-index, you will have to run a [special command](http://forum.cockos.com/showpost.php?p=1684115&postcount=413) to make the new index.file compatible.
I let you follow the development of this tool on the thread :)

I close this thread as I consider you have answer it.

Thanks you again for your work, and to your translator !

**Comment by X-Raym** [comment]
I see that you don't have index.xml anymore...
Did you have any issue with ReaPack ?
Let us know, and we could help you if needed ! :)

**Comment by kawaCat** [comment]
sorry my reply late !

this repo's ReaPack "index.xml" have exist in  [here](https://github.com/kawaCat/ReaScript-MidiPack). :)
there my "ReaScript-MidiPack" github Repository which was create for publish to ReaPack. 
its very similer name as in this repo. so its case had made confusing . sorry !

**Comment by X-Raym** [comment]
oh ok, cool ! :)
why have you separate repo ?
do you update both simultaneously ?

**Comment by kawaCat** [comment]
thanks ! :)

its has 2 reasons.
i dont know how to categorise  by reapack-index comment notation in src header. and I wanted "pre ReaPack folder" as testing or like beta version.

my script has depend on other lua file.for simplisity (to single file without depends), it need to combine these dependent files.  so i have need pre folder for testing or checking (combined/expected process) . this repo's MIDIPack folder is this. :)

**Comment by X-Raym** [comment]
It is ok to use file dependcy with ReaPack script as :

- Users often download the whole package
- You can define dependcy in the script header. they will be downloaded if one particular script is choosen instead of the whole pack
- There is a way to prevent some scripts files to be imported in the Action Lists

I think a good practice is to have only one version of a script hosted at one place.
Currently, you share your scripts on two repos, in three versions (reapack, minified with dependcy and usual), which may a bit confusing for the regular users and not that handy to manage for you (for updating a script, for bug reporting, etc).

Tell us what you need to know about ReaPack so we can help you :P
