### ISSUE TITLE
FR: Direction Indicator for Gonion Metter

### ISSUE THREAD

**Issue by X-Raym** [kawaCat/ReaScript-MIDI#3]
Hi !

Could your Gonion metter script have a direction Indicator like the [MStereoScope](https://www.meldaproduction.com/MStereoScope) ?

As you can see there is a segment that indicates the global direction of the stereo.

Having such feature could allow other users to build things around your pan analyzer system, like a graph over time of the stereo directivity of a track.

Cheers !

**Comment by kawaCat** [comment]
Hi ! thank you message :) 

 ( this message is not translated(not check syntax). if my english is wrong sorry)

i tried to visible direction Indicator like MStereoScope .
https://github.com/kawaCat/ReaScript-MIDI/wiki/GUI-Section#gonio-meter-test
does it feel ? 

and very very very thank you about reaper forums !!
i will repost message with translator. please wait little more.

**Comment by X-Raym** [comment]
Thanks ! it looks quite ok, it is not as precise as MStereoScope but It can definitely be used as a base for stereo analysis.
How pan is calculated ? Pre-FX, Pre-Fader or Post-Fader ?

You english is ok too, you may be better at english than you think 👍

**Comment by kawaCat** [comment]
> You english is ok too, you may be better at english than you think :+1:
wow !!  realy ?  Im very happy :)  in  fact , for the first time to message/chat  in english. ( + with google translate)

> How pan is calculated ? Pre-FX, Pre-Fader or Post-Fader ?
perhaps maybe. now ReaScript  can only get audio samples at  each  Items " Post Take Envelope " . this timing is before TCP controll .(  like between  from audio Item Clip  to TCP. )
so my scripts meters can move by Take Envelope volume/pan, and my scripts meters can not TCP fader controll and Midi Instruments metering.

if exist other way , I want to know that way. it will can do more freely audio script.

( if my english is not english . i will call translat guy again :+1: )

**Comment by X-Raym** [comment]
You see, you already made some progress at english ! Your translator sure could help you fine tune your speak but yiu can be understood by yourself !

There is indeed a way to have audio analysis post fader : use JSFX effects. It is the REAPER way to script FX that you can then put as track insert.
There is already a JSFX called gonionmeter but it miss the direction / ellipse thing. Also, there is a way to output value with JSFX so you could export the direction between 0 and 1 so tht it can be used for paramter modulation (ajusting another fx paramter according to pan direction and intensity), and it could also be accessed by ReaScript. It is has simple as creating a Slider for this direction.
The documentation for JSFX is on Cockos website.
If you succeed to mod this JSFX gonion metter thing it could be very cool !

**Comment by kawaCat** [comment]
wow ! very cool Nice Idea !!! 
this using JSFX  is I didnt inspiration answer . very cool !!!

and  I tried JSFXed my Gonion plugins . (now  yet only JSFX  .  i will try to  reaScript with JSFXed today  later )

JSFX  
[Gonion Meter image](https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/gonionMeter.PNG) 
[jsfx src] (https://github.com/kawaCat/ReaScript-MIDI/blob/master/https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/GonionMeter_Test.jsfx)

but my ellipse  function some times freezing..  :x

and I didnt  myself.
I did not think  thease a lot of eng words to speak.
I was worried about not saying that rude.

**Comment by X-Raym** [comment]
Nice that you like the idea !

Have you tried modifying the already exiting [Gonionmeter](http://reaperblog.net/2012/09/js-effect-spotlight-gfxgoniometer/) script built-in within REAPER, rather than coding your own from scratch ?
Starting from an existing script can be easier.
Also, if there is no JSFX ellipse function, maybe a simple [Diamond](https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Lozenge_-_black_simple.svg/220px-Lozenge_-_black_simple.svg.png) shape will be enough (and could be simpler to code :P)

**Comment by kawaCat** [comment]
ok !  

I will modify exiting reapers GonionMeter. And I think  also diamond pattern then. :-P

i m going to in bath times. please wait  modify coding :) little time.

**Comment by kawaCat** [comment]
hi ! 

I modified reapers GonionMeter !  on JSFX :) 

[Diamond Type Image ](https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/gfxGonio_Diamond.PNG)
[Ellipse Type Image](https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/gfxGonio_Ellipse.PNG)

[JSFX Src (kawa Mod)](https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/gfxGoniometer_kawaMod.jsfx)

 reapers GonionMeter's motion blur effect is dynamic !
 today or tommorrow / near , I will try to ReaScripts  with this GonioMeter JSFX :)

**Comment by X-Raym** [comment]
Impressive results already !

your direction analyser is a lot faster than MStereoScope !

- But as you can see the width of the diamond shape doesn't reveal any infos about the width of the audio. Do you think it could be possible to code ?

![Screenshot](http://i.imgur.com/6oNJzIh.gif)

- Ellipse shape doesn't seem to have the right orientation. [Screenshot](http://i.imgur.com/mHmLvNu.png).
- Also, I didn't succeed to output pan direction value as automation points when Play is on, I wonder what is wrong. I thought it would be possible but maybe I missed something.

That said, you already a really great job, bravo !

**Comment by kawaCat** [comment]
very Thank you  testing jsfx plugin !!

>  your direction analyser is a lot faster than MStereoScope !

wow !! non,non,  it faster code is reaper's Jesusonic execute code. :)
my code is not better perfomance. jsfx processor is very very optimize for only reaper. 
but MStereoScope is plugins ,and need compatibility stablity for any daws.

[JSFX Src (kawa Mod)](https://github.com/kawaCat/ReaScript-MIDI/blob/master/_test/gfxGoniometer_kawaMod.jsfx)

 I improved  ellipse function .(add draw ellipse outline ) and  I  will think  about  automation points  :)  In the near term.

thank you for !

**Comment by X-Raym** [comment]
Actually, you can run JSFX inside other DAW thanks to [ReaJS](http://www.reaper.fm/reaplugs/). :PNew ellipse design looks very good, I don't know how you succeed to do it without native function, that's impressive ! I will take a look at your code :P
Thanks for your work on this effects, it can open the door of a lot of good stuffs !

**Comment by kawaCat** [comment]
ReaJS  ! I didnt know this.  maybe we'll challenge to ReaJS DSP effect. 
reaper forum  is very Treasure Island :)

that ellipse function is from google seach :)
I getted at [ Draw Ellipse](http://www.softist.com/programming/drawcircle/drawcircle.htm) web page.
its jp page but i cant understood mathmatic things.
and  I copied and past to my script . then try and error and fix challenge.
so  I cant explain more matically or functionaly do this. :x

**Comment by hedacoder** [comment]
Kawa, I am very happy to see this. You are a genius :) I've always wanted to add this, but never had the time. I think  I'll make my Loudness Graph script compatible with your goniometer mod if the user installs the file. Thanks!

**Comment by kawaCat** [comment]
hi ! thank you message ! :) 

>  I am very happy to see this

me too !  very Thank you !
 I dont bielive Famous ReaScriptors of World ( X-Raym and hedacoder ) is Exist on this page !
Amazing !  Great Thing !  Very Super Thank you X-Raym and hedacoder !
You guys even genius :)

I am in very happy with your colaborations. 
i think the jsfx effect can take recieve OSC message from android or iphone/ipad /other .
it will ReaScript can access OSC message Data.maybe.
I think will do this thing  :)  I want to challenge controll to draw animation  from touch pad .
Thanks !

**Comment by X-Raym** [comment]
We are always happy to welcome new scripters !
(I didn't know we had this reputation haha ^^)

Good luck for the few improvements there is left on the Goniometer :) It is very close to be complete, which is exciting (heda and I were talking about having these JSFX features only few weeks ago, and you are makint them alive !) :P

**Comment by kawaCat** [comment]
Thank you X-Raym !  by the way, I learned about ReaScript  at X-Raym's [reference API page](http://extremraym.com/cloud/reascript/x-raym_reascripthelp.html) .

I had bookmarked this page already :)(^^)
I will do improvements Gonio just best .Thank you  a lot !

**Comment by kawaCat** [comment]
Hi ! Thank you for !  :)

 I improved and challenge GonioMeter with jsfx :)
 
jsfx 

[GonioMeter_Ex.jsfx](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/GonionMeter_Ex.jsfx)

ReaScript
* [kawa_GUI_GonioMeter_EX_Single.lua](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/kawa_GUI_GonioMeter_EX_Single.lua).
 This script dont have dependency other lua scripts.(can execute own single file).  but difficult reading src :x   ( If you do not mind, I reccommend this type. it is no exist loading bug.maybe)

* [kawa_GUI_GonioMeter_EX.lua](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/kawa_GUI_GonioMeter_EX.lua).
This script have dependency with "_kawa_GuiFunc2.lua".

![](https://github.com/kawaCat/ReaScript-MIDI/wiki/animGif/GonioMeter_EX_01.PNG)

[ Mouse | Controll  ]
Mouse Click Left   :  random BackGround color.
Mouse Click Right : step next Direction draw Type.[diamond or ellipse or box].
Mouse Click Middle(wheel Click) : start/stop Animation BackGround color.
Mouse Wheel : change BackGround color hue.

is it working ?  I worry . enjoy ! :)

**Comment by X-Raym** [comment]
Just tested your JSFX : seems quite good !
But it missed the Direction and Width slider parameter so we can output automation data or modulate a parameter with them.
Also, because it doesn't have the attack and release parameter like MeldaStereoScope, it is a bit shaky. Do you think it is possible to add these parameters (or others) to have a smoother Direction parameter ?
Also, maybe having MAXDRAWSPLS as a slider could be useful ?

Thanks for your work on it ! :)

PS : glad that you use my API doc style :smile:

**Comment by kawaCat** [comment]
Thank you testing ! :)

Automation parameter  is like adujst Detection speed parameter ? 
ok !  I added two params :) 
 "Direction Angle Speed" and "Value Speed" . I think  this parameters can adujst smoozing value. 
maybe. 

[GonioMeter_Ex.jsfx](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/GonionMeter_Ex.jsfx)

**Comment by X-Raym** [comment]
It seems to smooth the thing indeed. How does it works ?
It works pretty fine but there is some spike to the right (tested with mono source signal, panned at one direction).
[Screenshot](http://i.imgur.com/JmaB37U.gifv)

Also, having the [Direction slider](https://monosnap.com/file/ggOnnWLbLh0BInC8aI1GdMztXHisy4.png) back would be great, as it is thanks to it that we can modulate other parameter.

Little by little, we will make it work as expected :P

**Comment by kawaCat** [comment]
thanks !
it smooze process is "using last value way" .  it process is  get diference value between last value  and new value. then  add  this diference  value which divided by smooth number to last value .

``` c++
lastValue = 0.0 ;// first initilize
newValue = 1.0 ;// target example value
smooze = 5; // smooze setting num

lastValue = lastValue + ( newValue -lastValue) /smooze; 
// 0.0 + (1.0 -0.0) / 5 = 0.0 + 0.2  = 0.2 // 1st calc
// 0.2 +(1.0 -0.2 ) / 5 = 0.2 + 0.16  = 0.36 // 2nd calc
// 0.36+(1.0 -0.36) /5 = 0.36 + 0.128  = 0.488 // 3rd calc
// ...... .=. 1.0 
```
and cation very near in target Value ..  exist slowry case by using process ..  :x ( 1.00..1 ~ 0.999..9  repeat forward backword)
but its simple one line easing move function. :)

thanks ! ok! I visible back Direction Slider .
and I make simple mid side jsfx plugin for panning meter check .[simple Mid Side JSFX](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/Simple%20Mid%20Side.jsfx) .

that Screen shot Problem is very difficultry..  :x  my stereo direction process is ambiguous. I think using mid material and side material value way which can maybe resolve screen shot spike.

i tried  it .[GonionMeter_Ex](https://raw.githubusercontent.com/kawaCat/ReaScript-MIDI/master/ReaScript_MIDI/GUI/GonionMeter_Ex.jsfx). but difficultry.  :p

thank you !

**Comment by X-Raym** [comment]
That's clever !
Just tested the new smooth direction: sounds kinda cool ! Great job !

I think something went wrong with shapes: they are now very small.
Look how small the Diamond is on this [screenshot](https://monosnap.com/file/DFx8BFytqlsjwHmCxYfYjk5xQlwbsh.png).
Any idea about that ? :)

**Comment by X-Raym** [comment]
By looking at the EBUr128_analysis JSFX plugin, I succeed to make slider output automation data :)

![Screenshot](http://i.imgur.com/4v3Zlvq.gif)

I send you a pull request. :)

**Comment by kawaCat** [comment]
Thanks ! quick replay very helpfull.

small Diamond ' size is calculation at 

near line 243
``` c++
//====================================================================
function _drawDiamond(cx_,cy_,a_,b_,size_,rad)//cx_,cy_ is center points, a_,b_ is modulation value.(audio sample).size_ is lengh width.
  local (minV,maxV,_tempV,p1,p2,p3,p4)
(
    //================================================================
    p1.x = cx_ ; 
    p1.y = cy_ - size_*(a_*_lastMid/2); //  this line value "_lastMid" is Vertical Length to Top
    //================================================================
    p2.x = cx_ + size_*(b_*_lastSideR/2); //  this line  "_lastSideR" is Horizontal Length to R
    p2.y = cy_;
    //================================================================
    p3.x = cx_;
    p3.y = cy_ + size_*(a_*_lastMid/2); //  this  "_lastMid" is Vertical Length to Bottom
    //================================================================
    p4.x = cx_ - size_ *(b_*_lastSideL/2); //  this  "_lastSideR" is Horizontal Length to Left
    p4.y = cy_;
```

or  line 495 

```c++
//   Diamond  target length.  if increase ,then  it will be big length.
_size = sizeQ*(_max_L+_max_R)/2 *4; 
_lastSizeDiamond = _lastSizeDiamond + (_size-_lastSizeDiamond) /slider61; // one Line Easing function
```

wow !!  its automation data impressive ! emotional !  I will look this plugin src.

**Comment by X-Raym** [comment]
Pull request here :
https://github.com/kawaCat/ReaScript-MIDI/pull/4

Do you think you can fix the shapes size ? :)

**Comment by kawaCat** [comment]
wow !! its my first time pull request !! very super thank you !!    I will check now !

**Comment by kawaCat** [comment]
Very Thankyou !!   I checked automation ! 

thats smoll size..
I think "Using dB value  way"  which is maybe can resolve minimum sample value (smoll size).

I will try to. :)

**Comment by kawaCat** [comment]
I tried dB way (get decibel value which use to normarized ) :)  it is seems like beter than previous calc way. 
but sometime getted bigger value.  :x  this time too difficultly.

**Comment by X-Raym** [comment]
Let us know when you will want us to try :)
Thanks again for your work on this !

**Comment by hedacoder** [comment]
it seems Stereo Direction ( L C R ) is not affected by the Direction Angle Speed. Maybe there could be another output slider named "Stereo Direction Smooth"

very good work kawaCat :)

**Comment by kawaCat** [comment]
Super Thanks ! :) 

and  i  have confusioning how to use github. sorry for many commited. i think its   check is hard work .
sorry again

this version's is it working ? 
[ GonionMeter_EX(single).zip](https://github.com/kawaCat/ReaScript-MIDI/wiki/zip/GonionMeter_EX.zip)

in this zip's "GonionMeter_Ex.jsfx" ,  "Stereo Direction ( L C R )"  as "slider60"  is using at  line near 507~509.  its written in other lines other smooth process way group.

and my search  jsfx plugin function process was wrong in "kawa_GUI_GonioMeter_EX_Single.lua"  
its "string.find()" to "string.match()".  i think perhaps  contains other problems.  if find then  i will  try to fix.

**Comment by kawaCat** [comment]
if  want to use "Stereo Direction ( L C R )" 's parameter as  smoothed value ,

in @sample 
```
rad = atan2( _max_L,_max_R); // radian 0 ~ 90 
// slider2 =1.0- rad/($pi/2) ; //  comment out
```
 
add to @gfx 
```
// line end section
slider2 = slider2 + (rad -slider2 ) / slider60;
slider_automate(slider2);
```

it will  "Stereo Direction ( L C R )" 's parameter  with smoothing :)

**Comment by kawaCat** [comment]
-- closed. :)

**Comment by X-Raym** [comment]
did you solve the shape size issue ? :)

**Comment by kawaCat** [comment]
i hoped  you may cutomize source  by with yourself . 

in add function `` _drawDiamond_2() ``  ( but it maybe wrong , i think  it can more optimaze.)

and Please  you can translation guy . your english is difficultly with still me .(sorry)
in case of this, "shape size" confuse me  it  "which?"  "when?"  "log dB detection?"  "is not same as Ellipse width?"  im not Esper.  I dont like English .

**Comment by X-Raym** [comment]
Ok I 'll take a look at it :)

Thank you again !
