### ISSUE TITLE
Script Request: Increment chords notes channel

### ISSUE THREAD

**Issue by X-Raym** [kawaCat/ReaScript-MIDI#6]
Hi !

I tried to look at your script functions but it is way too advanced for me haha ^^ I never see anything like that, but the result is very good (your chord detection technics etc).

That's why I make a script request and I didn't try to make it myself:
I need an action that would be able to increment selected notes channel according to their position in a chord. It is meant to be used with guitar GFX script I am making, each channel represent a string on the guitar.

![Demo](https://monosnap.com/file/cOGQOSs7gSV7djMyPNAdO9ik9Hm4id.png)

Also, channel of bottom note, from which the other channel are calculated, should be the channel of the actual bottom notes (not 1 especially).

Are you intersted by this ? :)

(oh, did you see that I rebuild the [reascripts-doc](http://extremraym.com/cloud/reascript-doc) ? This can be helpful to you)

**Comment by kawaCat** [comment]
Hi ! :) thank you for ! 

( I can not understand reading english well. if I was get read as misstake  English ,sorry )

I think  my Lua code is  more tricky strange code.  so reading function process is difficultly.
In case of using Object-orientation in Lua lang ,usually  will use  like this  [middleclass] (https://github.com/kikito/middleclass). 

and usefull tool for Lua editor  here. :) 
[zerobrain Studio GitHub] ( https://github.com/pkulchenko/ZeroBraneStudio )
[zerobrain Studio]( https://studio.zerobrane.com/ )
I hope this tool be your helpfull.


I added scripts. "Increment / Decrement Channel.lua" and "Assign ChordTone By Channel.lua" . ( It may be wrong ).  "Assign ChordTone By Channel.lua"  will assign Incremented channel  from bottom note to Top note in detected chord tone.


Your reascripts-doc is Great !!
Thank you !  :)

**Comment by X-Raym** [comment]
OH thank you very much for that you don't know how much time you will save for me and users of my future guitar tab script :guitar: :tada: 

I'll check our infos. I like very much the Atom editor but maybe a Lua specific editor can answer different problems.

Your generosity is very appreciated :)

Cheers !

(ps I think your increment decrement channel script already exist as native action: Set MIDI events channel higher/lower... but maybe I miss a small difference ? anyway, that was a good idea !)

**Comment by kawaCat** [comment]
Thank you! yea ! 

 I did not know that action. perhaps its same result. maybe  ;)

**Comment by X-Raym** [comment]
If it is (I let you try), I advice you to remove your script from your pack in order to not confuse your users and to avoid having duplicate actions in the action list which may be a bit disturbing :)
