### ISSUE TITLE
Script Request: Select similar chords/notes pattern in MIDI take

### ISSUE THREAD

**Issue by X-Raym** [kawaCat/ReaScript-MIDI#7]
Hi Kawa :)

Recently I often had to do a special thing : selecting all chords with similar notes than the selecting ones (with or without consideration for note length, the two versions are possible).

![Input->Output](http://f.cl.ly/items/442X0b1D233p3m1Z1n2r/Image%202016-06-04%20at%2010.28.04%20AM.png)

An even more advanced version of this would be detect the pattern of selected notes and see if it is present somewhere else in the item, no matter if selected notes are chords or not. Example in the screenshot below: you would for select the two notes at the left, and it should be able to detect that this pattern can also be found later in the item.

![Demo](http://f.cl.ly/items/152q2H2R033W0p073G2Z/Image%202016-06-04%20at%2010.36.57%20AM.png)

I totally understood why this should be too hard. The minimal request (selecting strictly similar chords, with exact same notes duration) may be way more easy to do do than the last one.
Chords detection is so tricky with ReaScript, but maybe your system can answer such need without too much trouble ?

Let us know if this is possible,
Thanks again for your consideration ! 😸

**Comment by kawaCat** [comment]
I am thinking about it, and cannot say anything for sure right now... The new version will be the answer itself.

**Comment by kawaCat** [comment]
I am thinking about it, and cannot say anything for sure right now...
 The new version will be the answer itself.

**Comment by X-Raym** [comment]
Thanks for your consideration !
(don't worry, it is not a very high priority request)
